# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ sevrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/setup-node@v1
      with: 
        fetch=depth: 0
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
        cache: 'npm'
        
    - name: Install dependencies
      run: npm i
      
    - name: Run application  
      run: npm run start
      
    - name: Run tests
      run: npm test
