name: Node.js CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
        cache: 'npm'
        
    - run: npm i
    - run: npm run start
    - run: npm test
