name: Node.js CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    
    - run: npm i
    - run: npm run start
    - run: npm run test
